// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/proto/v1/coordinator.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskState enumerates all valid states in the task lifecycle.
type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_BLOCKED     TaskState = 2
	TaskState_TASK_STATE_READY       TaskState = 3
	TaskState_TASK_STATE_LEASED      TaskState = 4
	TaskState_TASK_STATE_RUNNING     TaskState = 5
	TaskState_TASK_STATE_SUCCEEDED   TaskState = 6
	TaskState_TASK_STATE_FAILED      TaskState = 7
	TaskState_TASK_STATE_RETRY_WAIT  TaskState = 8
	TaskState_TASK_STATE_CANCELLED   TaskState = 9
	TaskState_TASK_STATE_LOST        TaskState = 10
	TaskState_TASK_STATE_RECOVERING  TaskState = 11
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0:  "TASK_STATE_UNSPECIFIED",
		1:  "TASK_STATE_PENDING",
		2:  "TASK_STATE_BLOCKED",
		3:  "TASK_STATE_READY",
		4:  "TASK_STATE_LEASED",
		5:  "TASK_STATE_RUNNING",
		6:  "TASK_STATE_SUCCEEDED",
		7:  "TASK_STATE_FAILED",
		8:  "TASK_STATE_RETRY_WAIT",
		9:  "TASK_STATE_CANCELLED",
		10: "TASK_STATE_LOST",
		11: "TASK_STATE_RECOVERING",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_BLOCKED":     2,
		"TASK_STATE_READY":       3,
		"TASK_STATE_LEASED":      4,
		"TASK_STATE_RUNNING":     5,
		"TASK_STATE_SUCCEEDED":   6,
		"TASK_STATE_FAILED":      7,
		"TASK_STATE_RETRY_WAIT":  8,
		"TASK_STATE_CANCELLED":   9,
		"TASK_STATE_LOST":        10,
		"TASK_STATE_RECOVERING":  11,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_coordinator_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_api_proto_v1_coordinator_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

type TaskSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Priority       int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	PayloadType    string                 `protobuf:"bytes,6,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Dependencies   []string               `protobuf:"bytes,9,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *TaskSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskSpec) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TaskSpec) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskSpec) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *TaskSpec) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskSpec) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *TaskSpec) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskSpec) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TaskSpec) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskSpec              `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTaskRequest) GetTask() *TaskSpec {
	if x != nil {
		return x.Task
	}
	return nil
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State         TaskState              `protobuf:"varint,2,opt,name=state,proto3,enum=scheduler.v1.TaskState" json:"state,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitTaskResponse) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *SubmitTaskResponse) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

type SubmitDAGRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DagId         string                 `protobuf:"bytes,1,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Tasks         []*TaskSpec            `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDAGRequest) Reset() {
	*x = SubmitDAGRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDAGRequest) ProtoMessage() {}

func (x *SubmitDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDAGRequest.ProtoReflect.Descriptor instead.
func (*SubmitDAGRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitDAGRequest) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *SubmitDAGRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitDAGRequest) GetTasks() []*TaskSpec {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type SubmitDAGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DagId         string                 `protobuf:"bytes,1,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	TaskCount     int32                  `protobuf:"varint,2,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDAGResponse) Reset() {
	*x = SubmitDAGResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDAGResponse) ProtoMessage() {}

func (x *SubmitDAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDAGResponse.ProtoReflect.Descriptor instead.
func (*SubmitDAGResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitDAGResponse) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *SubmitDAGResponse) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

func (x *SubmitDAGResponse) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	DagId            string                 `protobuf:"bytes,2,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	State            TaskState              `protobuf:"varint,4,opt,name=state,proto3,enum=scheduler.v1.TaskState" json:"state,omitempty"`
	Priority         int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	AttemptCount     int32                  `protobuf:"varint,6,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	MaxRetries       int32                  `protobuf:"varint,7,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	AssignedWorkerId string                 `protobuf:"bytes,8,opt,name=assigned_worker_id,json=assignedWorkerId,proto3" json:"assigned_worker_id,omitempty"`
	LeaseEpoch       uint64                 `protobuf:"varint,9,opt,name=lease_epoch,json=leaseEpoch,proto3" json:"lease_epoch,omitempty"`
	Result           []byte                 `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResponse) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *GetTaskResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTaskResponse) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *GetTaskResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *GetTaskResponse) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *GetTaskResponse) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *GetTaskResponse) GetAssignedWorkerId() string {
	if x != nil {
		return x.AssignedWorkerId
	}
	return ""
}

func (x *GetTaskResponse) GetLeaseEpoch() uint64 {
	if x != nil {
		return x.LeaseEpoch
	}
	return 0
}

func (x *GetTaskResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetTaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetTaskResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetTaskResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetTaskResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GetDAGRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DagId         string                 `protobuf:"bytes,1,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDAGRequest) Reset() {
	*x = GetDAGRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDAGRequest) ProtoMessage() {}

func (x *GetDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDAGRequest.ProtoReflect.Descriptor instead.
func (*GetDAGRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *GetDAGRequest) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

type GetDAGResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DagId          string                 `protobuf:"bytes,1,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TotalTasks     int32                  `protobuf:"varint,3,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	PendingTasks   int32                  `protobuf:"varint,4,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	RunningTasks   int32                  `protobuf:"varint,5,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	SucceededTasks int32                  `protobuf:"varint,6,opt,name=succeeded_tasks,json=succeededTasks,proto3" json:"succeeded_tasks,omitempty"`
	FailedTasks    int32                  `protobuf:"varint,7,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	Tasks          []*GetTaskResponse     `protobuf:"bytes,8,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDAGResponse) Reset() {
	*x = GetDAGResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDAGResponse) ProtoMessage() {}

func (x *GetDAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDAGResponse.ProtoReflect.Descriptor instead.
func (*GetDAGResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *GetDAGResponse) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *GetDAGResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDAGResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *GetDAGResponse) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *GetDAGResponse) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *GetDAGResponse) GetSucceededTasks() int32 {
	if x != nil {
		return x.SucceededTasks
	}
	return 0
}

func (x *GetDAGResponse) GetFailedTasks() int32 {
	if x != nil {
		return x.FailedTasks
	}
	return 0
}

func (x *GetDAGResponse) GetTasks() []*GetTaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PreviousState TaskState              `protobuf:"varint,2,opt,name=previous_state,json=previousState,proto3,enum=scheduler.v1.TaskState" json:"previous_state,omitempty"`
	CurrentState  TaskState              `protobuf:"varint,3,opt,name=current_state,json=currentState,proto3,enum=scheduler.v1.TaskState" json:"current_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskResponse) GetPreviousState() TaskState {
	if x != nil {
		return x.PreviousState
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *CancelTaskResponse) GetCurrentState() TaskState {
	if x != nil {
		return x.CurrentState
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

type GetClusterHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterHealthRequest) Reset() {
	*x = GetClusterHealthRequest{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterHealthRequest) ProtoMessage() {}

func (x *GetClusterHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterHealthRequest.ProtoReflect.Descriptor instead.
func (*GetClusterHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{11}
}

type GetClusterHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsLeader      bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,4,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	CurrentTerm   uint64                 `protobuf:"varint,5,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,6,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	ActiveWorkers int32                  `protobuf:"varint,7,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	QueuedTasks   int32                  `protobuf:"varint,8,opt,name=queued_tasks,json=queuedTasks,proto3" json:"queued_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterHealthResponse) Reset() {
	*x = GetClusterHealthResponse{}
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterHealthResponse) ProtoMessage() {}

func (x *GetClusterHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterHealthResponse.ProtoReflect.Descriptor instead.
func (*GetClusterHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *GetClusterHealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetClusterHealthResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *GetClusterHealthResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *GetClusterHealthResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *GetClusterHealthResponse) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *GetClusterHealthResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *GetClusterHealthResponse) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *GetClusterHealthResponse) GetQueuedTasks() int32 {
	if x != nil {
		return x.QueuedTasks
	}
	return 0
}

var File_api_proto_v1_coordinator_proto protoreflect.FileDescriptor

const file_api_proto_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/v1/coordinator.proto\x12\fscheduler.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x02\n" +
	"\bTaskSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\x12!\n" +
	"\fpayload_type\x18\x06 \x01(\tR\vpayloadType\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12\"\n" +
	"\fdependencies\x18\t \x03(\tR\fdependencies\"?\n" +
	"\x11SubmitTaskRequest\x12*\n" +
	"\x04task\x18\x01 \x01(\v2\x16.scheduler.v1.TaskSpecR\x04task\"\x9b\x01\n" +
	"\x12SubmitTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.scheduler.v1.TaskStateR\x05state\x12=\n" +
	"\fsubmitted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\"t\n" +
	"\x10SubmitDAGRequest\x12\x15\n" +
	"\x06dag_id\x18\x01 \x01(\tR\x05dagId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12,\n" +
	"\x05tasks\x18\x03 \x03(\v2\x16.scheduler.v1.TaskSpecR\x05tasks\"\x88\x01\n" +
	"\x11SubmitDAGResponse\x12\x15\n" +
	"\x06dag_id\x18\x01 \x01(\tR\x05dagId\x12\x1d\n" +
	"\n" +
	"task_count\x18\x02 \x01(\x05R\ttaskCount\x12=\n" +
	"\fsubmitted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xb0\x04\n" +
	"\x0fGetTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06dag_id\x18\x02 \x01(\tR\x05dagId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12-\n" +
	"\x05state\x18\x04 \x01(\x0e2\x17.scheduler.v1.TaskStateR\x05state\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12#\n" +
	"\rattempt_count\x18\x06 \x01(\x05R\fattemptCount\x12\x1f\n" +
	"\vmax_retries\x18\a \x01(\x05R\n" +
	"maxRetries\x12,\n" +
	"\x12assigned_worker_id\x18\b \x01(\tR\x10assignedWorkerId\x12\x1f\n" +
	"\vlease_epoch\x18\t \x01(\x04R\n" +
	"leaseEpoch\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\fR\x06result\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"&\n" +
	"\rGetDAGRequest\x12\x15\n" +
	"\x06dag_id\x18\x01 \x01(\tR\x05dagId\"\xb0\x02\n" +
	"\x0eGetDAGResponse\x12\x15\n" +
	"\x06dag_id\x18\x01 \x01(\tR\x05dagId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtotal_tasks\x18\x03 \x01(\x05R\n" +
	"totalTasks\x12#\n" +
	"\rpending_tasks\x18\x04 \x01(\x05R\fpendingTasks\x12#\n" +
	"\rrunning_tasks\x18\x05 \x01(\x05R\frunningTasks\x12'\n" +
	"\x0fsucceeded_tasks\x18\x06 \x01(\x05R\x0esucceededTasks\x12!\n" +
	"\ffailed_tasks\x18\a \x01(\x05R\vfailedTasks\x123\n" +
	"\x05tasks\x18\b \x03(\v2\x1d.scheduler.v1.GetTaskResponseR\x05tasks\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xab\x01\n" +
	"\x12CancelTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12>\n" +
	"\x0eprevious_state\x18\x02 \x01(\x0e2\x17.scheduler.v1.TaskStateR\rpreviousState\x12<\n" +
	"\rcurrent_state\x18\x03 \x01(\x0e2\x17.scheduler.v1.TaskStateR\fcurrentState\"\x19\n" +
	"\x17GetClusterHealthRequest\"\xa4\x02\n" +
	"\x18GetClusterHealthResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x04 \x01(\tR\rleaderAddress\x12!\n" +
	"\fcurrent_term\x18\x05 \x01(\x04R\vcurrentTerm\x12!\n" +
	"\fcommit_index\x18\x06 \x01(\x04R\vcommitIndex\x12%\n" +
	"\x0eactive_workers\x18\a \x01(\x05R\ractiveWorkers\x12!\n" +
	"\fqueued_tasks\x18\b \x01(\x05R\vqueuedTasks*\xb2\x02\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_BLOCKED\x10\x02\x12\x14\n" +
	"\x10TASK_STATE_READY\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_LEASED\x10\x04\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x05\x12\x18\n" +
	"\x14TASK_STATE_SUCCEEDED\x10\x06\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\a\x12\x19\n" +
	"\x15TASK_STATE_RETRY_WAIT\x10\b\x12\x18\n" +
	"\x14TASK_STATE_CANCELLED\x10\t\x12\x13\n" +
	"\x0fTASK_STATE_LOST\x10\n" +
	"\x12\x19\n" +
	"\x15TASK_STATE_RECOVERING\x10\v2\xf4\x03\n" +
	"\x12CoordinatorService\x12O\n" +
	"\n" +
	"SubmitTask\x12\x1f.scheduler.v1.SubmitTaskRequest\x1a .scheduler.v1.SubmitTaskResponse\x12L\n" +
	"\tSubmitDAG\x12\x1e.scheduler.v1.SubmitDAGRequest\x1a\x1f.scheduler.v1.SubmitDAGResponse\x12F\n" +
	"\aGetTask\x12\x1c.scheduler.v1.GetTaskRequest\x1a\x1d.scheduler.v1.GetTaskResponse\x12C\n" +
	"\x06GetDAG\x12\x1b.scheduler.v1.GetDAGRequest\x1a\x1c.scheduler.v1.GetDAGResponse\x12O\n" +
	"\n" +
	"CancelTask\x12\x1f.scheduler.v1.CancelTaskRequest\x1a .scheduler.v1.CancelTaskResponse\x12a\n" +
	"\x10GetClusterHealth\x12%.scheduler.v1.GetClusterHealthRequest\x1a&.scheduler.v1.GetClusterHealthResponseB0Z.distributed-scheduler/api/proto/v1;schedulerv1b\x06proto3"

var (
	file_api_proto_v1_coordinator_proto_rawDescOnce sync.Once
	file_api_proto_v1_coordinator_proto_rawDescData []byte
)

func file_api_proto_v1_coordinator_proto_rawDescGZIP() []byte {
	file_api_proto_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_coordinator_proto_rawDesc), len(file_api_proto_v1_coordinator_proto_rawDesc)))
	})
	return file_api_proto_v1_coordinator_proto_rawDescData
}

var file_api_proto_v1_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_v1_coordinator_proto_goTypes = []any{
	(TaskState)(0),                   // 0: scheduler.v1.TaskState
	(*TaskSpec)(nil),                 // 1: scheduler.v1.TaskSpec
	(*SubmitTaskRequest)(nil),        // 2: scheduler.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),       // 3: scheduler.v1.SubmitTaskResponse
	(*SubmitDAGRequest)(nil),         // 4: scheduler.v1.SubmitDAGRequest
	(*SubmitDAGResponse)(nil),        // 5: scheduler.v1.SubmitDAGResponse
	(*GetTaskRequest)(nil),           // 6: scheduler.v1.GetTaskRequest
	(*GetTaskResponse)(nil),          // 7: scheduler.v1.GetTaskResponse
	(*GetDAGRequest)(nil),            // 8: scheduler.v1.GetDAGRequest
	(*GetDAGResponse)(nil),           // 9: scheduler.v1.GetDAGResponse
	(*CancelTaskRequest)(nil),        // 10: scheduler.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),       // 11: scheduler.v1.CancelTaskResponse
	(*GetClusterHealthRequest)(nil),  // 12: scheduler.v1.GetClusterHealthRequest
	(*GetClusterHealthResponse)(nil), // 13: scheduler.v1.GetClusterHealthResponse
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_api_proto_v1_coordinator_proto_depIdxs = []int32{
	1,  // 0: scheduler.v1.SubmitTaskRequest.task:type_name -> scheduler.v1.TaskSpec
	0,  // 1: scheduler.v1.SubmitTaskResponse.state:type_name -> scheduler.v1.TaskState
	14, // 2: scheduler.v1.SubmitTaskResponse.submitted_at:type_name -> google.protobuf.Timestamp
	1,  // 3: scheduler.v1.SubmitDAGRequest.tasks:type_name -> scheduler.v1.TaskSpec
	14, // 4: scheduler.v1.SubmitDAGResponse.submitted_at:type_name -> google.protobuf.Timestamp
	0,  // 5: scheduler.v1.GetTaskResponse.state:type_name -> scheduler.v1.TaskState
	14, // 6: scheduler.v1.GetTaskResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 7: scheduler.v1.GetTaskResponse.started_at:type_name -> google.protobuf.Timestamp
	14, // 8: scheduler.v1.GetTaskResponse.completed_at:type_name -> google.protobuf.Timestamp
	7,  // 9: scheduler.v1.GetDAGResponse.tasks:type_name -> scheduler.v1.GetTaskResponse
	0,  // 10: scheduler.v1.CancelTaskResponse.previous_state:type_name -> scheduler.v1.TaskState
	0,  // 11: scheduler.v1.CancelTaskResponse.current_state:type_name -> scheduler.v1.TaskState
	2,  // 12: scheduler.v1.CoordinatorService.SubmitTask:input_type -> scheduler.v1.SubmitTaskRequest
	4,  // 13: scheduler.v1.CoordinatorService.SubmitDAG:input_type -> scheduler.v1.SubmitDAGRequest
	6,  // 14: scheduler.v1.CoordinatorService.GetTask:input_type -> scheduler.v1.GetTaskRequest
	8,  // 15: scheduler.v1.CoordinatorService.GetDAG:input_type -> scheduler.v1.GetDAGRequest
	10, // 16: scheduler.v1.CoordinatorService.CancelTask:input_type -> scheduler.v1.CancelTaskRequest
	12, // 17: scheduler.v1.CoordinatorService.GetClusterHealth:input_type -> scheduler.v1.GetClusterHealthRequest
	3,  // 18: scheduler.v1.CoordinatorService.SubmitTask:output_type -> scheduler.v1.SubmitTaskResponse
	5,  // 19: scheduler.v1.CoordinatorService.SubmitDAG:output_type -> scheduler.v1.SubmitDAGResponse
	7,  // 20: scheduler.v1.CoordinatorService.GetTask:output_type -> scheduler.v1.GetTaskResponse
	9,  // 21: scheduler.v1.CoordinatorService.GetDAG:output_type -> scheduler.v1.GetDAGResponse
	11, // 22: scheduler.v1.CoordinatorService.CancelTask:output_type -> scheduler.v1.CancelTaskResponse
	13, // 23: scheduler.v1.CoordinatorService.GetClusterHealth:output_type -> scheduler.v1.GetClusterHealthResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_v1_coordinator_proto_init() }
func file_api_proto_v1_coordinator_proto_init() {
	if File_api_proto_v1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_coordinator_proto_rawDesc), len(file_api_proto_v1_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_coordinator_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_coordinator_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_coordinator_proto_msgTypes,
	}.Build()
	File_api_proto_v1_coordinator_proto = out.File
	file_api_proto_v1_coordinator_proto_goTypes = nil
	file_api_proto_v1_coordinator_proto_depIdxs = nil
}
