// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/proto/v1/worker.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MaxSlots      int32                  `protobuf:"varint,3,opt,name=max_slots,json=maxSlots,proto3" json:"max_slots,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterWorkerRequest) GetMaxSlots() int32 {
	if x != nil {
		return x.MaxSlots
	}
	return 0
}

func (x *RegisterWorkerRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterWorkerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RegisterWorkerResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Accepted            bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	LeaderId            string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	HeartbeatIntervalMs int64                  `protobuf:"varint,3,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	LeaseDurationMs     int64                  `protobuf:"varint,4,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterWorkerResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *RegisterWorkerResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *RegisterWorkerResponse) GetLeaseDurationMs() int64 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

type ActiveLeaseHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseEpoch    uint64                 `protobuf:"varint,2,opt,name=lease_epoch,json=leaseEpoch,proto3" json:"lease_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveLeaseHeartbeat) Reset() {
	*x = ActiveLeaseHeartbeat{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveLeaseHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveLeaseHeartbeat) ProtoMessage() {}

func (x *ActiveLeaseHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveLeaseHeartbeat.ProtoReflect.Descriptor instead.
func (*ActiveLeaseHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ActiveLeaseHeartbeat) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ActiveLeaseHeartbeat) GetLeaseEpoch() uint64 {
	if x != nil {
		return x.LeaseEpoch
	}
	return 0
}

type HeartbeatRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	WorkerId        string                  `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AvailableSlots  int32                   `protobuf:"varint,2,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	ActiveLeases    []*ActiveLeaseHeartbeat `protobuf:"bytes,3,rep,name=active_leases,json=activeLeases,proto3" json:"active_leases,omitempty"`
	ClientTimestamp *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	SessionId       string                  `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveLeases() []*ActiveLeaseHeartbeat {
	if x != nil {
		return x.ActiveLeases
	}
	return nil
}

func (x *HeartbeatRequest) GetClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTimestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged   bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	RevokedTaskIds []string               `protobuf:"bytes,2,rep,name=revoked_task_ids,json=revokedTaskIds,proto3" json:"revoked_task_ids,omitempty"` // Tasks whose leases expired or were reclaimed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetRevokedTaskIds() []string {
	if x != nil {
		return x.RevokedTaskIds
	}
	return nil
}

type PullTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AvailableSlots int32                  `protobuf:"varint,2,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PullTaskRequest) Reset() {
	*x = PullTaskRequest{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTaskRequest) ProtoMessage() {}

func (x *PullTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTaskRequest.ProtoReflect.Descriptor instead.
func (*PullTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *PullTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PullTaskRequest) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

func (x *PullTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TaskAssignment struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	DagId              string                 `protobuf:"bytes,2,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Priority           int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	LeaseEpoch         uint64                 `protobuf:"varint,5,opt,name=lease_epoch,json=leaseEpoch,proto3" json:"lease_epoch,omitempty"`
	LeaseDurationMs    int64                  `protobuf:"varint,6,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"`
	ExecutionTimeoutMs int64                  `protobuf:"varint,7,opt,name=execution_timeout_ms,json=executionTimeoutMs,proto3" json:"execution_timeout_ms,omitempty"`
	PayloadType        string                 `protobuf:"bytes,8,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Payload            []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	SessionId          string                 `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *TaskAssignment) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TaskAssignment) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskAssignment) GetLeaseEpoch() uint64 {
	if x != nil {
		return x.LeaseEpoch
	}
	return 0
}

func (x *TaskAssignment) GetLeaseDurationMs() int64 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

func (x *TaskAssignment) GetExecutionTimeoutMs() int64 {
	if x != nil {
		return x.ExecutionTimeoutMs
	}
	return 0
}

func (x *TaskAssignment) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *TaskAssignment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PullTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasTask       bool                   `protobuf:"varint,1,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	Assignment    *TaskAssignment        `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTaskResponse) Reset() {
	*x = PullTaskResponse{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTaskResponse) ProtoMessage() {}

func (x *PullTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTaskResponse.ProtoReflect.Descriptor instead.
func (*PullTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *PullTaskResponse) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *PullTaskResponse) GetAssignment() *TaskAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type AckTaskRunningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseEpoch    uint64                 `protobuf:"varint,3,opt,name=lease_epoch,json=leaseEpoch,proto3" json:"lease_epoch,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckTaskRunningRequest) Reset() {
	*x = AckTaskRunningRequest{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckTaskRunningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckTaskRunningRequest) ProtoMessage() {}

func (x *AckTaskRunningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckTaskRunningRequest.ProtoReflect.Descriptor instead.
func (*AckTaskRunningRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *AckTaskRunningRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AckTaskRunningRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AckTaskRunningRequest) GetLeaseEpoch() uint64 {
	if x != nil {
		return x.LeaseEpoch
	}
	return 0
}

func (x *AckTaskRunningRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AckTaskRunningRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AckTaskRunningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckTaskRunningResponse) Reset() {
	*x = AckTaskRunningResponse{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckTaskRunningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckTaskRunningResponse) ProtoMessage() {}

func (x *AckTaskRunningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckTaskRunningResponse.ProtoReflect.Descriptor instead.
func (*AckTaskRunningResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *AckTaskRunningResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *AckTaskRunningResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportTaskCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseEpoch    uint64                 `protobuf:"varint,3,opt,name=lease_epoch,json=leaseEpoch,proto3" json:"lease_epoch,omitempty"`
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskCompletedRequest) Reset() {
	*x = ReportTaskCompletedRequest{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskCompletedRequest) ProtoMessage() {}

func (x *ReportTaskCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskCompletedRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskCompletedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *ReportTaskCompletedRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportTaskCompletedRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskCompletedRequest) GetLeaseEpoch() uint64 {
	if x != nil {
		return x.LeaseEpoch
	}
	return 0
}

func (x *ReportTaskCompletedRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReportTaskCompletedRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ReportTaskCompletedRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ReportTaskCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskCompletedResponse) Reset() {
	*x = ReportTaskCompletedResponse{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskCompletedResponse) ProtoMessage() {}

func (x *ReportTaskCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskCompletedResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskCompletedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{11}
}

func (x *ReportTaskCompletedResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportTaskCompletedResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportTaskFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseEpoch    uint64                 `protobuf:"varint,3,opt,name=lease_epoch,json=leaseEpoch,proto3" json:"lease_epoch,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Retryable     bool                   `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	FailedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskFailedRequest) Reset() {
	*x = ReportTaskFailedRequest{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskFailedRequest) ProtoMessage() {}

func (x *ReportTaskFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskFailedRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskFailedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{12}
}

func (x *ReportTaskFailedRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportTaskFailedRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskFailedRequest) GetLeaseEpoch() uint64 {
	if x != nil {
		return x.LeaseEpoch
	}
	return 0
}

func (x *ReportTaskFailedRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportTaskFailedRequest) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ReportTaskFailedRequest) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *ReportTaskFailedRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ReportTaskFailedResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged     bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	WillRetry        bool                   `protobuf:"varint,2,opt,name=will_retry,json=willRetry,proto3" json:"will_retry,omitempty"`
	RemainingRetries int32                  `protobuf:"varint,3,opt,name=remaining_retries,json=remainingRetries,proto3" json:"remaining_retries,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportTaskFailedResponse) Reset() {
	*x = ReportTaskFailedResponse{}
	mi := &file_api_proto_v1_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskFailedResponse) ProtoMessage() {}

func (x *ReportTaskFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskFailedResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskFailedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_worker_proto_rawDescGZIP(), []int{13}
}

func (x *ReportTaskFailedResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportTaskFailedResponse) GetWillRetry() bool {
	if x != nil {
		return x.WillRetry
	}
	return false
}

func (x *ReportTaskFailedResponse) GetRemainingRetries() int32 {
	if x != nil {
		return x.RemainingRetries
	}
	return 0
}

func (x *ReportTaskFailedResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_v1_worker_proto protoreflect.FileDescriptor

const file_api_proto_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/worker.proto\x12\fscheduler.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\tmax_slots\x18\x03 \x01(\x05R\bmaxSlots\x12M\n" +
	"\bmetadata\x18\x04 \x03(\v21.scheduler.v1.RegisterWorkerRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\x16RegisterWorkerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x03 \x01(\x03R\x13heartbeatIntervalMs\x12*\n" +
	"\x11lease_duration_ms\x18\x04 \x01(\x03R\x0fleaseDurationMs\"P\n" +
	"\x14ActiveLeaseHeartbeat\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_epoch\x18\x02 \x01(\x04R\n" +
	"leaseEpoch\"\x87\x02\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12'\n" +
	"\x0favailable_slots\x18\x02 \x01(\x05R\x0eavailableSlots\x12G\n" +
	"\ractive_leases\x18\x03 \x03(\v2\".scheduler.v1.ActiveLeaseHeartbeatR\factiveLeases\x12E\n" +
	"\x10client_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientTimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"a\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12(\n" +
	"\x10revoked_task_ids\x18\x02 \x03(\tR\x0erevokedTaskIds\"v\n" +
	"\x0fPullTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12'\n" +
	"\x0favailable_slots\x18\x02 \x01(\x05R\x0eavailableSlots\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xd4\x02\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06dag_id\x18\x02 \x01(\tR\x05dagId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vlease_epoch\x18\x05 \x01(\x04R\n" +
	"leaseEpoch\x12*\n" +
	"\x11lease_duration_ms\x18\x06 \x01(\x03R\x0fleaseDurationMs\x120\n" +
	"\x14execution_timeout_ms\x18\a \x01(\x03R\x12executionTimeoutMs\x12!\n" +
	"\fpayload_type\x18\b \x01(\tR\vpayloadType\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\n" +
	" \x01(\tR\tsessionId\"k\n" +
	"\x10PullTaskResponse\x12\x19\n" +
	"\bhas_task\x18\x01 \x01(\bR\ahasTask\x12<\n" +
	"\n" +
	"assignment\x18\x02 \x01(\v2\x1c.scheduler.v1.TaskAssignmentR\n" +
	"assignment\"\xc8\x01\n" +
	"\x15AckTaskRunningRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_epoch\x18\x03 \x01(\x04R\n" +
	"leaseEpoch\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"a\n" +
	"\x16AckTaskRunningResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xe9\x01\n" +
	"\x1aReportTaskCompletedRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_epoch\x18\x03 \x01(\x04R\n" +
	"leaseEpoch\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"f\n" +
	"\x1bReportTaskCompletedResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x8b\x02\n" +
	"\x17ReportTaskFailedRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_epoch\x18\x03 \x01(\x04R\n" +
	"leaseEpoch\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable\x127\n" +
	"\tfailed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"\xaf\x01\n" +
	"\x18ReportTaskFailedResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1d\n" +
	"\n" +
	"will_retry\x18\x02 \x01(\bR\twillRetry\x12+\n" +
	"\x11remaining_retries\x18\x03 \x01(\x05R\x10remainingRetries\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\xb1\x04\n" +
	"\rWorkerService\x12[\n" +
	"\x0eRegisterWorker\x12#.scheduler.v1.RegisterWorkerRequest\x1a$.scheduler.v1.RegisterWorkerResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.scheduler.v1.HeartbeatRequest\x1a\x1f.scheduler.v1.HeartbeatResponse\x12I\n" +
	"\bPullTask\x12\x1d.scheduler.v1.PullTaskRequest\x1a\x1e.scheduler.v1.PullTaskResponse\x12[\n" +
	"\x0eAckTaskRunning\x12#.scheduler.v1.AckTaskRunningRequest\x1a$.scheduler.v1.AckTaskRunningResponse\x12j\n" +
	"\x13ReportTaskCompleted\x12(.scheduler.v1.ReportTaskCompletedRequest\x1a).scheduler.v1.ReportTaskCompletedResponse\x12a\n" +
	"\x10ReportTaskFailed\x12%.scheduler.v1.ReportTaskFailedRequest\x1a&.scheduler.v1.ReportTaskFailedResponseB0Z.distributed-scheduler/api/proto/v1;schedulerv1b\x06proto3"

var (
	file_api_proto_v1_worker_proto_rawDescOnce sync.Once
	file_api_proto_v1_worker_proto_rawDescData []byte
)

func file_api_proto_v1_worker_proto_rawDescGZIP() []byte {
	file_api_proto_v1_worker_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_worker_proto_rawDesc), len(file_api_proto_v1_worker_proto_rawDesc)))
	})
	return file_api_proto_v1_worker_proto_rawDescData
}

var file_api_proto_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_v1_worker_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),       // 0: scheduler.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),      // 1: scheduler.v1.RegisterWorkerResponse
	(*ActiveLeaseHeartbeat)(nil),        // 2: scheduler.v1.ActiveLeaseHeartbeat
	(*HeartbeatRequest)(nil),            // 3: scheduler.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 4: scheduler.v1.HeartbeatResponse
	(*PullTaskRequest)(nil),             // 5: scheduler.v1.PullTaskRequest
	(*TaskAssignment)(nil),              // 6: scheduler.v1.TaskAssignment
	(*PullTaskResponse)(nil),            // 7: scheduler.v1.PullTaskResponse
	(*AckTaskRunningRequest)(nil),       // 8: scheduler.v1.AckTaskRunningRequest
	(*AckTaskRunningResponse)(nil),      // 9: scheduler.v1.AckTaskRunningResponse
	(*ReportTaskCompletedRequest)(nil),  // 10: scheduler.v1.ReportTaskCompletedRequest
	(*ReportTaskCompletedResponse)(nil), // 11: scheduler.v1.ReportTaskCompletedResponse
	(*ReportTaskFailedRequest)(nil),     // 12: scheduler.v1.ReportTaskFailedRequest
	(*ReportTaskFailedResponse)(nil),    // 13: scheduler.v1.ReportTaskFailedResponse
	nil,                                 // 14: scheduler.v1.RegisterWorkerRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
}
var file_api_proto_v1_worker_proto_depIdxs = []int32{
	14, // 0: scheduler.v1.RegisterWorkerRequest.metadata:type_name -> scheduler.v1.RegisterWorkerRequest.MetadataEntry
	2,  // 1: scheduler.v1.HeartbeatRequest.active_leases:type_name -> scheduler.v1.ActiveLeaseHeartbeat
	15, // 2: scheduler.v1.HeartbeatRequest.client_timestamp:type_name -> google.protobuf.Timestamp
	6,  // 3: scheduler.v1.PullTaskResponse.assignment:type_name -> scheduler.v1.TaskAssignment
	15, // 4: scheduler.v1.AckTaskRunningRequest.started_at:type_name -> google.protobuf.Timestamp
	15, // 5: scheduler.v1.ReportTaskCompletedRequest.completed_at:type_name -> google.protobuf.Timestamp
	15, // 6: scheduler.v1.ReportTaskFailedRequest.failed_at:type_name -> google.protobuf.Timestamp
	0,  // 7: scheduler.v1.WorkerService.RegisterWorker:input_type -> scheduler.v1.RegisterWorkerRequest
	3,  // 8: scheduler.v1.WorkerService.Heartbeat:input_type -> scheduler.v1.HeartbeatRequest
	5,  // 9: scheduler.v1.WorkerService.PullTask:input_type -> scheduler.v1.PullTaskRequest
	8,  // 10: scheduler.v1.WorkerService.AckTaskRunning:input_type -> scheduler.v1.AckTaskRunningRequest
	10, // 11: scheduler.v1.WorkerService.ReportTaskCompleted:input_type -> scheduler.v1.ReportTaskCompletedRequest
	12, // 12: scheduler.v1.WorkerService.ReportTaskFailed:input_type -> scheduler.v1.ReportTaskFailedRequest
	1,  // 13: scheduler.v1.WorkerService.RegisterWorker:output_type -> scheduler.v1.RegisterWorkerResponse
	4,  // 14: scheduler.v1.WorkerService.Heartbeat:output_type -> scheduler.v1.HeartbeatResponse
	7,  // 15: scheduler.v1.WorkerService.PullTask:output_type -> scheduler.v1.PullTaskResponse
	9,  // 16: scheduler.v1.WorkerService.AckTaskRunning:output_type -> scheduler.v1.AckTaskRunningResponse
	11, // 17: scheduler.v1.WorkerService.ReportTaskCompleted:output_type -> scheduler.v1.ReportTaskCompletedResponse
	13, // 18: scheduler.v1.WorkerService.ReportTaskFailed:output_type -> scheduler.v1.ReportTaskFailedResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_v1_worker_proto_init() }
func file_api_proto_v1_worker_proto_init() {
	if File_api_proto_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_worker_proto_rawDesc), len(file_api_proto_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_worker_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_worker_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_worker_proto_msgTypes,
	}.Build()
	File_api_proto_v1_worker_proto = out.File
	file_api_proto_v1_worker_proto_goTypes = nil
	file_api_proto_v1_worker_proto_depIdxs = nil
}
