// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: api/proto/v1/worker.proto

package schedulerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_RegisterWorker_FullMethodName      = "/scheduler.v1.WorkerService/RegisterWorker"
	WorkerService_Heartbeat_FullMethodName           = "/scheduler.v1.WorkerService/Heartbeat"
	WorkerService_PullTask_FullMethodName            = "/scheduler.v1.WorkerService/PullTask"
	WorkerService_AckTaskRunning_FullMethodName      = "/scheduler.v1.WorkerService/AckTaskRunning"
	WorkerService_ReportTaskCompleted_FullMethodName = "/scheduler.v1.WorkerService/ReportTaskCompleted"
	WorkerService_ReportTaskFailed_FullMethodName    = "/scheduler.v1.WorkerService/ReportTaskFailed"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService defines RPCs invoked by worker daemons to interact with the coordinator.
type WorkerServiceClient interface {
	// RegisterWorker registers a new or restarting worker daemon with the coordinator leader.
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	// Heartbeat periodically reports worker liveness and renews active task leases.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// PullTask is invoked by a worker when it has available execution slots (Worker-Pull model).
	PullTask(ctx context.Context, in *PullTaskRequest, opts ...grpc.CallOption) (*PullTaskResponse, error)
	// AckTaskRunning is sent by a worker immediately when task execution begins.
	AckTaskRunning(ctx context.Context, in *AckTaskRunningRequest, opts ...grpc.CallOption) (*AckTaskRunningResponse, error)
	// ReportTaskCompleted reports successful task completion with execution output.
	ReportTaskCompleted(ctx context.Context, in *ReportTaskCompletedRequest, opts ...grpc.CallOption) (*ReportTaskCompletedResponse, error)
	// ReportTaskFailed reports a failed task execution with error details.
	ReportTaskFailed(ctx context.Context, in *ReportTaskFailedRequest, opts ...grpc.CallOption) (*ReportTaskFailedResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) PullTask(ctx context.Context, in *PullTaskRequest, opts ...grpc.CallOption) (*PullTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullTaskResponse)
	err := c.cc.Invoke(ctx, WorkerService_PullTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) AckTaskRunning(ctx context.Context, in *AckTaskRunningRequest, opts ...grpc.CallOption) (*AckTaskRunningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckTaskRunningResponse)
	err := c.cc.Invoke(ctx, WorkerService_AckTaskRunning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReportTaskCompleted(ctx context.Context, in *ReportTaskCompletedRequest, opts ...grpc.CallOption) (*ReportTaskCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskCompletedResponse)
	err := c.cc.Invoke(ctx, WorkerService_ReportTaskCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReportTaskFailed(ctx context.Context, in *ReportTaskFailedRequest, opts ...grpc.CallOption) (*ReportTaskFailedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskFailedResponse)
	err := c.cc.Invoke(ctx, WorkerService_ReportTaskFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService defines RPCs invoked by worker daemons to interact with the coordinator.
type WorkerServiceServer interface {
	// RegisterWorker registers a new or restarting worker daemon with the coordinator leader.
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	// Heartbeat periodically reports worker liveness and renews active task leases.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// PullTask is invoked by a worker when it has available execution slots (Worker-Pull model).
	PullTask(context.Context, *PullTaskRequest) (*PullTaskResponse, error)
	// AckTaskRunning is sent by a worker immediately when task execution begins.
	AckTaskRunning(context.Context, *AckTaskRunningRequest) (*AckTaskRunningResponse, error)
	// ReportTaskCompleted reports successful task completion with execution output.
	ReportTaskCompleted(context.Context, *ReportTaskCompletedRequest) (*ReportTaskCompletedResponse, error)
	// ReportTaskFailed reports a failed task execution with error details.
	ReportTaskFailed(context.Context, *ReportTaskFailedRequest) (*ReportTaskFailedResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedWorkerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServiceServer) PullTask(context.Context, *PullTaskRequest) (*PullTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullTask not implemented")
}
func (UnimplementedWorkerServiceServer) AckTaskRunning(context.Context, *AckTaskRunningRequest) (*AckTaskRunningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckTaskRunning not implemented")
}
func (UnimplementedWorkerServiceServer) ReportTaskCompleted(context.Context, *ReportTaskCompletedRequest) (*ReportTaskCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskCompleted not implemented")
}
func (UnimplementedWorkerServiceServer) ReportTaskFailed(context.Context, *ReportTaskFailedRequest) (*ReportTaskFailedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskFailed not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_PullTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).PullTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_PullTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).PullTask(ctx, req.(*PullTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_AckTaskRunning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckTaskRunningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).AckTaskRunning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_AckTaskRunning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).AckTaskRunning(ctx, req.(*AckTaskRunningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReportTaskCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReportTaskCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReportTaskCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReportTaskCompleted(ctx, req.(*ReportTaskCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReportTaskFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReportTaskFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReportTaskFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReportTaskFailed(ctx, req.(*ReportTaskFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _WorkerService_RegisterWorker_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerService_Heartbeat_Handler,
		},
		{
			MethodName: "PullTask",
			Handler:    _WorkerService_PullTask_Handler,
		},
		{
			MethodName: "AckTaskRunning",
			Handler:    _WorkerService_AckTaskRunning_Handler,
		},
		{
			MethodName: "ReportTaskCompleted",
			Handler:    _WorkerService_ReportTaskCompleted_Handler,
		},
		{
			MethodName: "ReportTaskFailed",
			Handler:    _WorkerService_ReportTaskFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/worker.proto",
}
